# Puppet Forge
forge "https://forgeapi.puppetlabs.com"

# mod, <module name>, <version or tag>, <source>
mod 'puppetlabs/apache'
mod 'puppetlabs/apt'
mod 'collectd',
  :git => 'git://github.com/pdxcat/puppet-module-collectd.git'
mod 'puppetlabs/concat' 
mod 'puppetlabs/firewall'
mod 'graphite',
  :git => 'git://github.com/echocat/puppet-graphite.git'
mod 'ldap',
  :git => 'git://github.com/datacentred/datacentred-ldap.git'
mod 'puppetlabs/nodejs'
mod 'puppetlabs/ntp'  
mod 'herculesteam/augeasproviders_core'
mod 'herculesteam/augeasproviders_shellvar'
mod 'shibboleth',
  :git => 'git://github.com/Aethylred/puppet-shibboleth.git'
mod 'statsd',
  :git => 'git://github.com/justindowning/puppet-statsd.git'
mod 'puppetlabs/stdlib'  

