#!/usr/bin/env ruby
#^syntax detection

forge "https://forgeapi.puppetlabs.com"

# mod, <module name>, <version or tag>, <source>
mod 'puppetlabs-apt'
mod 'puppetlabs-ntp'
mod 'saz-timezone'
mod 'puppetlabs-apache'
mod 'pdxcat-collectd',
  :git => 'git://github.com/pdxcat/puppet-module-collectd.git'
mod 'puppetlabs-concat' 
mod 'puppetlabs-firewall'
mod 'echocat-graphite',
  :git => 'git://github.com/echocat/puppet-graphite.git'
mod 'datacentred-ldap'
mod 'puppetlabs-nodejs'
#mod 'puppetlabs/ntp'  
mod 'herculesteam-augeasproviders_core'
mod 'herculesteam-augeasproviders_shellvar'
mod 'Aethylred-shibboleth',
  :git => 'git://github.com/Aethylred/puppet-shibboleth.git'
mod 'justindowning-statsd',
  :git => 'git://github.com/justindowning/puppet-statsd.git'
mod 'puppetlabs-stdlib'  
mod 'puppetlabs-haproxy'
mod 'puppetlabs-java'
mod 'puppetlabs-java_ks'
mod 'puppetlabs-tomcat',
  :git => 'git://github.com/puppetlabs/puppetlabs-tomcat.git'
mod 'thias-sysctl'
mod 'wikimedia-jmxtrans',
  :git => 'git://github.com/wikimedia/puppet-jmxtrans.git'
